// Products Data
const products = [
  { id: 1, name: 'Fresh Potatoes', price: 30, unit: 'kg', farmer: 'Ramesh Kumar', location: 'Punjab', rating: 4.5, image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=400&fit=crop', category: 'vegetables', freshness: 95, harvestDate: '2025-09-28' },
  { id: 2, name: 'Organic Rice', price: 80, unit: 'kg', farmer: 'Suresh Patel', location: 'Haryana', rating: 4.8, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop', category: 'grains', freshness: 100, harvestDate: '2025-09-25' },
  { id: 3, name: 'Fresh Mangoes', price: 120, unit: 'kg', farmer: 'Anjali Sharma', location: 'Maharashtra', rating: 4.9, image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=400&fit=crop', category: 'fruits', freshness: 92, harvestDate: '2025-09-29' },
  { id: 4, name: 'Green Peas', price: 60, unit: 'kg', farmer: 'Mohan Singh', location: 'UP', rating: 4.3, image: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=400&h=400&fit=crop', category: 'vegetables', freshness: 88, harvestDate: '2025-09-27' },
  { id: 5, name: 'Wheat Flour', price: 45, unit: 'kg', farmer: 'Geeta Devi', location: 'Rajasthan', rating: 4.6, image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=400&fit=crop', category: 'grains', freshness: 100, harvestDate: '2025-09-20' },
  { id: 6, name: 'Fresh Apples', price: 150, unit: 'kg', farmer: 'Ravi Verma', location: 'Himachal', rating: 4.7, image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=400&fit=crop', category: 'fruits', freshness: 90, harvestDate: '2025-09-28' },
  { id: 7, name: 'Fresh Carrots', price: 35, unit: 'kg', farmer: 'Sunita Devi', location: 'Punjab', rating: 4.4, image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop', category: 'vegetables', freshness: 93, harvestDate: '2025-09-29' },
  { id: 8, name: 'Fresh Bananas', price: 50, unit: 'dozen', farmer: 'Prakash Kumar', location: 'Kerala', rating: 4.6, image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop', category: 'fruits', freshness: 94, harvestDate: '2025-09-30' }
];

const farmTools = [
  { id: 1, name: 'Power Tiller', price: 85000, image: 'https://images.unsplash.com/photo-1581578949510-fa7315c4c350?w=400&h=400&fit=crop', discount: 12, description: 'Versatile power tiller for soil preparation and cultivation', brand: 'AgriPower' },
  { id: 2, name: 'Seeds Package', price: 2000, image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=400&fit=crop', discount: 15, description: 'Premium quality seeds for high yield', brand: 'Seeds Co' },
  { id: 3, name: 'Fertilizers', price: 1500, image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=400&fit=crop', discount: 5, description: 'Organic fertilizers for healthy crops', brand: 'AgriChem' },
  { id: 4, name: 'Sprayer Machine', price: 12000, image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=400&fit=crop&sat=-100', discount: 10, description: 'Advanced sprayer for pesticides and fertilizers application', brand: 'SprayTech' }
];

const weatherData = {
  temperature: 28,
  humidity: 65,
  rainfall: 'Moderate',
  suggestedCrops: ['Rice', 'Cotton', 'Sugarcane', 'Maize'],
  season: 'Kharif'
};

const translations = {
  en: {
    appName: "Farm2Market",
    marketplace: "Marketplace",
    myProducts: "My Products",
    orders: "Orders",
    tools: "Farm Tools",
    weather: "Weather & Crop Suggestion",
    profile: "Profile",
    searchPlaceholder: "Search for fresh produce...",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    login: "Login",
    register: "Register",
    farmerView: "Farmer View",
    customerView: "Customer View",
    allCategories: "All Categories",
    proceedCheckout: "Proceed to Checkout",
    cartEmpty: "Your cart is empty",
    cartTitle: "Shopping Cart",
    remove: "Remove",
    clearAll: "Clear All",
    unitKg: "kg",
    categories: { vegetables: "Vegetables", fruits: "Fruits", grains: "Grains" },
    loginTitle: "Login to Farm2Market",
    registerTitle: "Register",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    altPhoneNumber: "Alternate Phone Number (optional)",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    iAmA: "I am a",
    favoriteFood: "Favorite Food",
    favoriteColor: "Favorite Color",
    myProductsTitle: "My Products",
    addNewProduct: "Add New Product",
    tableHeaders: { product: "Product", price: "Price", stock: "Stock", status: "Status", actions: "Actions" },
    active: "Active",
    myOrdersTitle: "My Orders",
    orderLabel: "Order",
    placedOn: "Placed on",
    inTransit: "In Transit",
    fromLabel: "From",
    trackOrder: "Track Order",
    agriToolsTitle: "Agricultural Tools & Supplies",
    viewDetails: "View Details",
    totalLabel: "Total",
    orderSummaryTitle: "Order Summary",
    proceedToPayment: "Proceed to Payment",
    paymentTitle: "Payment",
    nameOnCard: "Name on Card",
    cardNumber: "Card Number",
    expiry: "Expiry",
    cvv: "CVV",
    backToSummary: "Back to Summary",
    payNow: "Pay Now",
    paymentSuccess: "Payment successful!",
    deliveryAddress: "Delivery Address",
    editAddress: "Change / Edit",
    addressLine: "Address Line",
    city: "City",
    state: "State",
    pincode: "Pincode",
    saveAddress: "Save Address",
    deliverySlot: "Delivery Slot",
    chooseSlot: "Choose a delivery slot",
    today: "Today",
    tomorrow: "Tomorrow",
    priceDetails: "Price Details",
    itemsTotal: "Items Total",
    discountLabel: "Discount",
    deliveryFee: "Delivery Fee",
    free: "Free",
    payable: "Amount Payable",
    continue: "Continue",
    stepCart: "Cart",
    stepAddress: "Address",
    stepSummary: "Order Summary",
    stepPayment: "Payment",
    upiOptionsTitle: "UPI Options",
    paytm: "Paytm",
    gpay: "Google Pay",
    phonepe: "PhonePe",
    amazonpay: "Amazon Pay",
    cod: "Cash on Delivery",
    secure100: "100% Secure",
    back: "Back",
    flatBuilding: "Flat / House / Building Name",
    addressType: "Address Type",
    home: "Home",
    work: "Work",
    useMyLocation: "Use my current location",
    savedAddresses: "Saved Addresses",
    addNewAddress: "Add New Address",
    currentlySelected: "Currently selected",
    edit: "Edit",
    aboutUs: "About Us",
    aboutCompany: "About Company",
    help: "Help",
    wishlist: "Wishlist"
  },
  hi: {
    appName: "फार्म2मार्केट",
    marketplace: "बाज़ार",
    myProducts: "मेरे उत्पाद",
    orders: "आदेश",
    tools: "कृषि उपकरण",
    weather: "मौसम और फसल सुझाव",
    profile: "प्रोफ़ाइल",
    searchPlaceholder: "ताजा उत्पाद खोजें...",
    addToCart: "कार्ट में डालें",
    buyNow: "अभी खरीदें",
    login: "लॉग इन",
    register: "पंजीकरण",
    farmerView: "किसान दृश्य",
    customerView: "उपभोक्ता दृश्य",
    allCategories: "सभी श्रेणियाँ",
    proceedCheckout: "चेकआउट करें",
    cartEmpty: "आपकी कार्ट खाली है",
    cartTitle: "शॉपिंग कार्ट",
    remove: "हटाएं",
    clearAll: "सब साफ करें",
    unitKg: "किलो",
    categories: { vegetables: "सब्जियाँ", fruits: "फल", grains: "अनाज" },
    aboutUs: "हमारे बारे में",
    aboutCompany: "कंपनी के बारे में",
    help: "मदद",
    wishlist: "इच्छा सूची"
  },
  bn: {
    appName: "ফার্ম২মার্কেট",
    marketplace: "মার্কেটপ্লেস",
    myProducts: "আমার পণ্য",
    orders: "অর্ডার",
    tools: "কৃষি সরঞ্জাম",
    weather: "আবহাওয়া ও ফসল পরামর্শ",
    profile: "প্রোফাইল",
    searchPlaceholder: "তাজা পণ্য খুঁজুন...",
    addToCart: "কার্টে যোগ করুন",
    buyNow: "এখনই কিনুন",
    login: "লগইন",
    register: "রেজিস্টার",
    farmerView: "চাষী ভিউ",
    customerView: "ভোক্তা ভিউ",
    allCategories: "সব ক্যাটাগরি",
    proceedCheckout: "চেকআউট করুন",
    cartEmpty: "আপনার কার্ট খালি",
    cartTitle: "শপিং কার্ট",
    remove: "মুছুন",
    clearAll: "সব মুছুন",
    unitKg: "কেজি",
    categories: { vegetables: "সবজি", fruits: "ফল", grains: "শস্য" },
    aboutUs: "আমাদের সম্পর্কে",
    aboutCompany: "কোম্পানি সম্পর্কে",
    help: "সাহায্য",
    wishlist: "ইচ্ছা তালিকা"
  }
};
